### ISSUE TITLE
The with_deps global api has a known issue in the test mockup environment

### ISSUE THREAD

**Issue by brew0722** [line/cosmwasm#184]
I added one more api also for `deps`(https://github.com/line/cosmwasm/pull/182/commits/c15602b92d798edcee90cd7789d89c467f9a3747).
but It has one problem. it's like as existing architecture violation.

It hasn't problem based on product code because deps is stateless.
However, it has problem based on test code because mock deps has state.
But I need deps to implement the sample contract logic of Virtual callstack right now, so I add it first.

_Originally posted by @brew0722 in https://github.com/line/cosmwasm/issues/182#issuecomment-1092472157_

**Comment by loloicci** [comment]
closed via #213 and related PRs
