### ISSUE TITLE
workflow error in benchmark caused by dependency on not existing jobs

### ISSUE THREAD

**Issue by loloicci** [line/cosmwasm#208]
https://github.com/line/cosmwasm/actions/runs/2458631737

caused by

https://github.com/line/cosmwasm/blob/f9556df98904defef9a6e20c6a773ce30ecad8e9/.github/workflows/benchmarking.yml#L21

**Comment by shiki-tak** [comment]
It is due to the fact that the job was deleted with the following PR.
https://github.com/line/cosmwasm/pull/132

**Comment by loloicci** [comment]
Nice found!
We should add the dependent jobs, or move the benchmark job to another workflow.
