### ISSUE TITLE
Reconsider how to get deps and env in callee functions

### ISSUE THREAD

**Issue by loloicci** [line/cosmwasm#213]
Now we use `GlobalApi` for getting deps and env in callee functions. Consider getting them as parameters or improving `GlobalApi` for tests. (See `GlobalApi`'s fixme comments)

related: #212 and #184

**Comment by loloicci** [comment]
# About `deps`
I suggest adding `deps` as an arg of dynamic-linked function.

From

```
#[callable_point]
fn add(by: i32) {
    GlobalApi::with_deps_mut(|deps| handle_add(deps, by)).unwrap();
}
```

Into

```
#[callable_point]
fn add(deps: DepsMut, by: i32) {
    handle_add(deps, by).unwrap()
}
```

# About `env`
There are no problems technically. But, if we add `deps` as an arg of dynamic-linked function, It may be natural there is the `env` an arg, too.

**Comment by tnasu** [comment]
@shiki-tak @da1suk8 
How about yours?

**Comment by shiki-tak** [comment]
Question about deps
If we select Suggestion2, do we need to add `deps_name = deps` even if I don't use deps? (i.e. `deps_name = _deps`)

My opinion
I think the following suggestion is better because it is familiar as the way to write entry_point.
```
#[callable_point]
fn env(_deps: DepsMut, env: Environment, by: i32) {
    env
}
```

**Comment by loloicci** [comment]
> If we select Suggestion2, do we need to add `deps_name = deps` even if I don't use deps? (i.e. `deps_name = _deps`)

No, `deps_name` is optional. If there are no, the expanded one is `fn add(_deps: DepsMut, by: i32)` or `fn add(deps: DepsMut, by: i32)` by our macro defining default.

**Comment by da1suk8** [comment]
Regarding the **`deps`**, I think **Suggestion1** is better, because it is easier to see where the variables are coming from compared to Suggestion2.

Regarding **`env`**, I think **Suggestion2** is better, because I think it is cleaner to use it in the same way as **`deps`**.
