### ISSUE TITLE
Check the behavior when contract tries to open a file and fix it

### ISSUE THREAD

**Issue by da1suk8** [line/cosmwasm#219]
- Check for errors when a contract tries to open a file.
- Contract that should not be stored (contract that try to open a file) is stored.

This contract should not be stored and needs to be fixed.

**Comment by da1suk8** [comment]
- Goal : The contract, which should not be stored or executed, can be stored and executed in line/cosmwasm, so check and modify it.  
  - Add the following code and check by execute(instantiate, migrate), query
    1.   line/cosmwasm(main branch) 
    2.  cosmwasm/cosmwasm
    3.  line/cosmwasm(dynamic_link branch) 

  - If there is a difference between the above results, correct the behavior (where should it fall? etc...) and correct it. 
  - If there is no difference as a result of the above, correct the behavior (where should it fall? etc...) and where can it actually be executed? If it seems to be possible to fix it, then fix it.



 


```Rust
use std::fs::File;
use std::io::prelude::*;
   
fn check_store(filename: String) {
    let mut f = File::open(filename).expect("file not found");
   
    let mut contents = String::new();
    f.read_to_string(&mut contents)
        .expect("something went wrong reading the file");
 
}
```

**Comment by da1suk8** [comment]
It seems that cosmwasm/cosmwasm has a limitation that it is not supported on this platform.
I will fix it accordingly.
I plan to modify not only the dynamic_link branch but also the main branch.

```
raw_log: 'failed to execute message; message index: 0: Error calling the VM: Error
executing Wasm: Wasmer runtime error: RuntimeError: Aborted: panicked at ''file
not found: Error { kind: Unsupported, message: "operation not supported on this
platform" }'', src/contract.rs:43:38: execute wasm contract failed'
```

**Comment by da1suk8** [comment]
**Conculusion**

In cosmwasm/cosmwasm(line/cosmwasm), target=wasm32-unknown-unknown is used, so that std::fs functions return runtime errors at executing. Therefore, as for File::open, it cannot be executed.
- [about std::fs of wasm32-unknown-unknown](https://doc.rust-lang.org/rustc/platform-support/wasm64-unknown-unknown.html#:~:text=This%20target%20is%20cross%2Dcompiled.%20The%20target%20supports%20std%20in%20the%20same%20manner%20as%20the%20wasm32%2Dunknown%2Dunknown%20target%20which%20is%20to%20say%20that%20it%20comes%20with%20the%20standard%20library%20but%20many%20I/O%20functions%20such%20as%20std%3A%3Afs%20and%20std%3A%3Anet%20will%20simply%20return%20error)
- [wasm32-unknown-unknown](https://doc.rust-lang.org/stable/nightly-rustc/rustc_target/spec/wasm32_unknown_unknown/index.html)
- https://github.com/rust-lang/rust/pull/45905
- https://github.com/rust-lang/rust/blob/a7851767419e56280110fe2859bbc15d5cbdd468/library/std/src/sys/wasm/mod.rs#L1-L15
- https://github.com/rust-lang/rust/blob/8c6ce6b91b172f77c795a74bfeaf74b865146b3f/library/std/src/sys/unsupported/common.rs#L19-L24
- [https://crates.io/crates/platforms](https://crates.io/crates/platforms)

In addition, when compiled with target=wasm32-wasi using WASI, for which File::open, etc. is standardized, and tried to do store of wasm, an error occurred in validation.

- https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/src/compatibility.rs#L54-L62
- https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/src/compatibility.rs#L146-L171
- https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/src/compatibility.rs#L10-L30


Although there is a difference in the error contents between cosmwasm/cosmwasm and line/cosmwasm, the location causing the error is the same, and adding an abort feature as shown below will result in the same error contents.

- https://github.com/CosmWasm/cosmwasm/issues/1296

**Comment by loloicci** [comment]
@da1suk8 Could you try the wasm32-wasi version WASM in the dynamic link branch version LBM? The error "Wasm contract requires unsupported import" seems not to occur in dynamic link branch. It is because of this change (https://github.com/line/cosmwasm/blame/dynamic_link/packages/vm/src/compatibility.rs#L116).

**Comment by da1suk8** [comment]
The following error occurred during instantiate in the dynamic link branch. It seems that execution itself is not possible.

```
{"height":"789","txhash":"85A99B66B0B3A58D19947F2A7A81FDA5882AFA95BD6937D2FA5E55EA24BECD76","codespace":"wasm","code":4,"data":"","raw_log":"failed to execute message; message index: 0: Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: Error in guest/host communication: Got an invalid region: Got a zero Wasm address in the offset: instantiate wasm contract failed","logs":[],"info":"","gas_wanted":"10000000000","gas_used":"63259","tx":null,"timestamp":""}
```

Also, the following modification(https://github.com/line/cosmwasm/blame/dynamic_link/packages/vm/src/compatibility.rs#L116) to the dynamic link branch causes functions such as wasi_snapshot_preview1.fd_filestat_get to be judged as functions used by dynamic link when compiled by wasm32-wasi, etc. I have created [a new issue](https://github.com/line/cosmwasm/issues/243).
