### ISSUE TITLE
Check and fix on custom env module name

### ISSUE THREAD

**Issue by da1suk8** [line/cosmwasm#243]
In dynamic link, names other than env are judged as module to be used in dynamic link.
Thus, for example, `wasi_snapshot_preview1.fd_filestat_get` generated by `wasm32-wasi` is judged as a module used in dynamic link.

https://github.com/line/cosmwasm/blame/dynamic_link/packages/vm/src/compatibility.rs#L116

If it is necessary to separate the dynamic link module from the other modules, make the necessary modifications.

**Comment by loloicci** [comment]
closed via #248
