### ISSUE TITLE
Proposed method for read/write context/permission problems

### ISSUE THREAD

**Issue by da1suk8** [line/cosmwasm#264]
https://github.com/line/cosmwasm/issues/263

The following is a summary of methods to solve this problem.

---
**Add prefix to functions to manage read-only, read/write**

-  Use different macros for read-only and read-write
    - ex) `readonly_callable_point` / `read_write_callable_point`
    - It is easy to understand because read and read/write can be used in different macros
    - Usability will be reduced due to the increased number of writing rules
    - Migration to other languages may be difficult due to the use of rust-specific macros.
 

- Since `make_callable_point` internally determines **deps** and **depsmut**, we can use it to consider how to tell read only and read/write to the outside world.
    - https://github.com/line/cosmwasm/blob/d08b5a59115cc3d28f375b7425b902bfd1dac6a4/packages/derive/src/callable_point.rs#L29-L48
    - It is possible to get information about **deps** or **depsmut** from `TokenStream`, which is the return value of `make_callable_point`.
    - However, it is not a good idea to do parse.

- When connecting with dynamic_link macro, I need to know whether it is a readonly function or a read/write function. (Because you have to specify the prefix).
    - https://github.com/line/cosmwasm/blob/aba70a28303620156b42fb51d499aeb931f36eeb/packages/derive/src/dynamic_link.rs#L82
    - https://github.com/line/cosmwasm/blob/aba70a28303620156b42fb51d499aeb931f36eeb/packages/derive/src/lib.rs#L180-L185

---
**WASM has meta information, etc., to manage read-only and read/write**

- If there is a way to have meta-information in WASM, manage read-only and read-write with it.
     - Is it possible to have data for each function, or to have information such as headers? etc.
---

**Control functions used in dynamic link by dividing them into read-only or read/write and manage read-only and read/write functions**

- Manage dynamic_linked functions with read-only and read-write, and check the context when executing executes and queries.
    - Since prefixes are not added to function names, name collisions are unlikely to occur.

**Comment by loloicci** [comment]
> Since make_callable_point internally determines deps and depsmut, we can use it to consider how to tell read only and read/write to the outside world.

It is concerning that a function uses `Deps` and needs "read/write" permission. It happens if the function does not need to modify the storage and needs to execute other functions' "read/write" function.

How do you think about it?

**Comment by loloicci** [comment]
If there are two dynamic call points `contract_call_execute` and `contract_call_query` instead of `contract_call` https://github.com/line/cosmwasm/blob/202cb816088829e177267b3aa2113e06f199f942/packages/vm/src/backend.rs#L140-L146, and `contract_call_execute` can be called only via `DepsMut`, it sounds good.

**Comment by da1suk8** [comment]
> It is concerning that a function uses Deps and needs "read/write" permission. It happens if the function does not need to modify the storage and needs to execute other functions' "read/write" function. This is because difference between Deps and DepsMut is imutable/mutable of the storage

I had not thought about this pattern....
I will think about it. Thank you.


What is the relationship between [this code](https://github.com/line/cosmwasm/blob/202cb816088829e177267b3aa2113e06f199f942/packages/vm/src/backend.rs#L140-L146) and `DepsMut`?

**Comment by loloicci** [comment]
> What is the relationship between [this code](https://github.com/line/cosmwasm/blob/202cb816088829e177267b3aa2113e06f199f942/packages/vm/src/backend.rs#L140-L146) and DepsMut?

As I said

> Sorry, I was confused cosmwasm_vm::BackendApi and cosmwasm_std::Api, 

They are not related to each other now. Sorry for confusing you. But, if they have a relationship as below, I think it is cool.

> but I think it is cool that DepsMut has permission to execute read/write callable points.

**Comment by loloicci** [comment]
One more.

> It is possible to get information about deps or depsmut from TokenStream, which is the return value of make_callable_point.

Even if `callable_point` macro automatically judges whether the function is read-only or read/write, `dynamic_link` macro cannot. So, user must use `readonly_dynamic_link` and `readwrite_dynamic_link` properly. (This is because function name inside wasm will differ between readonly and readwrite.)  It sounds unuseful for users that use `callable_point` for all callee functions, and use readonly and readwrite version `dynamic_link` by infering the function is readonly or readwrite.

**Comment by da1suk8** [comment]
@loloicci 

You mean that it is inconvenient to use dynamic link macros to determine read-only or read/write, because the user must specify read-only or read/write in the arguments, etc. (because dynamic link macros cannot determine read-only or read/write), right?

**Comment by da1suk8** [comment]
I am thinking of adding a prefix to the caller function to distinguish between read-only and read-write for the read/write problem. (cosmwasm side)
I think this will reduce the amount of code in wasmvm.
Here is wasmvm: https://github.com/da1suk8/wasmvm/commit/9dc8e3d8320c905ab1988d6f88eeca2b2feffe2a

What do you think?

**Comment by loloicci** [comment]
How about makes a new function to publish the dynamic link function's properties as a required function (https://github.com/line/cosmwasm/blob/6ea2dfb77929c901fa8629df5c7753457b546860/packages/vm/src/compatibility.rs#L37)? For example, `list_callable_points` returns a map from functions to properties (read-only/read-write)

**Comment by da1suk8** [comment]
I have already implemented a way to solve this problem by creating a new function instead of prefixing it with the name of the function as a string indicating whether the function is read-only or read/write.
FYI: https://github.com/da1suk8/cosmwasm/commit/cd7acd8c7e6ce39d3cd0e83de8a626d27888d960, https://github.com/da1suk8/wasmvm/commit/3a84498679da193a049ac1bab41d66c65058db46

However, I think I can implement another method of creating a new function (to determine read-only or read/write in the function), so I would like to create this one, compare the two, and choose the better one.

Thanks.

**Comment by da1suk8** [comment]
By defining the following structure in contract of `cosmwasm`, 
I was able to retrieve a map of callee functions in `wasmvm`, which I would like to use to solve this problem.

```
struct CalleeMap<K, V> {
    inner: Vec<(K, V)>,
}

let m = CalleeMap {
    inner: vec![
        ("add", (false, "0.1.0")),
        ("sub", (false, "0.2.0")),
        ("mul", (false, "0.3.0")),
        ("number", (true, "0.1.0")),
    ],
};
```

In `wasmvm`, data can be extracted as a HashMap as shown below.

```
{"add": (false, "0.1.0"), "sub": (false, "0.3.0"), "mul": (false, "0.2.0"), "number": (true, "0.1.0")}
```

Thanks

**Comment by da1suk8** [comment]
There were two options for creating a macro: nightly version or stable version.

In the nightly version, the macro is applied on a per-module basis using the inner attribute.

https://doc.rust-lang.org/beta/unstable-book/language-features/proc-macro-hygiene.html
https://doc.rust-lang.org/beta/unstable-book/language-features/custom-inner-attributes.html

And this is sample code, https://github.com/loloicci/inner-attribute-macro-to-module-file, thank you.
When nightly version -> stable version, you may consider adapting.

However, currently, in order to build nightly version, a build tool for nightly version must be created separately from https://github.com/CosmWasm/rust-optimizer．

To solve this problem in this time, we'll implement the above `CalleeMap` using macro, which can be implemented with the `stable version`.

Thank you for your cooperation.
